---
- hosts: linuxservers
  become: yes
  become_user: root
  #assume user on system is named 'ansible' and has wheel role in users. assume ssh copy id used and no passphrase for ssh key
  tasks: 

  - name: update packages
    become: true
    become_user: root
    command:
      cmd: 'pacman -Syuu --noconfirm'
      
  - name: update packages
    become: true
    become_user: root
    command:
      cmd: 'pacman -Syyu --noconfirm'
      
  - name: Update package database and install required packages
    become: true
    become_user: root
    pacman:
      update_cache: yes
      state: present
      name:
        - lib32-gcc-libs
        - base-devel
        - linux-headers
        - tmux
        - git
        - ponysay
        - cowsay
        - fortune-mod
        - wget
        - curl

  - name: create directory for cs2 server
    file:
      path: /home/ansible/cs2server
      state: directory
      
   #- name: Ensure destination directory exists
   #   file:
   #     path: '/path/to/destination/directory'
   #     state: directory
   #     mode: '0755'



  - name: dl and install steamcmd
    unarchive:
      src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
      dest: /home/ansible/cs2server
      remote_src: yes

  - name: make the thing owned
    become: true
    become_user: root
    command: 
      cmd: "chown ansible:ansible -R /home/ansible/"

  - name: make steamcmd.sh executable?
    become: true
    become_user: root
    command:
      cmd: 'chmod +x /home/ansible/cs2server/steamcmd.sh'
      chdir: /home/ansible/cs2server

  # - name: Copy .so file to new location
  #    copy:
  #      src: '/path/where/tarball/was/extracted/somefile.so'
  #     dest: '/path/to/destination/directory/somefile.so'

  # - name: Copy .so file to new location
  #    copy:
  #      src: '/path/where/tarball/was/extracted/somefile.so'
  #     dest: '/path/to/destination/directory/somefile.so'


  - name: get update script
    command:
      cmd: 'wget https://gist.githubusercontent.com/cmcsun/231a5a6ac08e81176bd6fe80d41ca14b/raw/f55f6d00c925451bd1759d7f029f791f3b37a213/cs2update.sh'
      chdir: /home/ansible

  - name: make update script executable
    become: true
    become_user: root
    command:
      cmd: 'chmod +x cs2update.sh'
      chdir: /home/ansible

  - name: make everything owned by user
    become: true
    become_user: root
    command:
      cmd: "chown ansible:ansible -R /home/ansible"
      chdir: /home/ansible

  #task here to copy .so file to new location(s)
  #
  #can we run the script with ansible and have it fork to background? something with tmux involved im sure

#may need to update script before run!!!

#todo: run scipt which will login to steamcmd (must run steamcmd and log in to account beofre running script)

        #  - name: run cs2update.sh
        #    command:
        #      cmd
